repos:
  - repo: https://github.com/psf/black
    rev: "22.1.0"
    hooks:
      - id: black
        additional_dependencies: [ "click==8.0.4" ]
        language_version: python3
        files: "^python/"
        args: [
          "--config", "pyproject.toml",
        ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
          "--profile", "black",
          "--skip-glob", "python/ansible/plugins",
          "--skip", "python/init_db.py",
          "--skip", "python/task_runner.py",
          "--skip", "python/backupdb.py",
          "--skip", "python/job_runner.py",
          "--skip", "python/drf_docs.py",
        ]
        language_version: python3
        files: "^python/"

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [
          "-rn",
          "-sn",
          "--rcfile=pyproject.toml",
        ]
